# Generated by Django 2.2.16 on 2021-11-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20211105_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
