# Generated by Django 2.2.16 on 2021-11-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211111_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
